Agregando configuración de mysql en las puebas de python para CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -500,17 +500,66 @@ jobs:
 
       - name: Start the Docker containers
         run: |
-           docker-compose up --no-build --detach
+          docker-compose up --no-build --detach
 
-           # Add the container names as aliases to localhost
-           cat << EOF | sudo tee --append /etc/hosts
-           127.0.0.1 rabbitmq mysql
-           EOF
+          # Add the container names as aliases to localhost
+          cat << EOF | sudo tee --append /etc/hosts
+          127.0.0.1 rabbitmq mysql
+          EOF
 
-           # Wait for some of the containers
-           wait-for-it -t 30 mysql:13306
-           wait-for-it -t 30 rabbitmq:5672
-           docker-compose exec -T rabbitmq rabbitmqctl await_startup
+          # Wait for some of the containers
+          wait-for-it -t 30 mysql:13306
+          wait-for-it -t 30 rabbitmq:5672
+          docker-compose exec -T rabbitmq rabbitmqctl await_startup
+
+          for i in $(seq 10); do
+            if [[ "$(mysql \
+                    -uomegaup -pomegaup --host=mysql --port= 13306 --skip-column-names --batch \
+                    -e 'SELECT 1;' || echo 0)" == "1" ]]; then
+              break
+            fi
+            sleep 1
+          done
+
+      - name: Create default configuration files
+        run: |
+          cat > frontend/server/config.php <<EOF
+          <?php
+          define('OMEGAUP_ALLOW_PRIVILEGE_SELF_ASSIGNMENT', true);
+          define('OMEGAUP_CSP_LOG_FILE', '/tmp/csp.log');
+          define('OMEGAUP_DB_HOST', 'mysql');
+          define('OMEGAUP_DB_NAME', 'omegaup');
+          define('OMEGAUP_DB_PASS', 'omegaup');
+          define('OMEGAUP_DB_USER', 'omegaup');
+          define('OMEGAUP_ENVIRONMENT', 'development');
+          define('OMEGAUP_LOG_FILE', '/tmp/omegaup.log');
+          define('OMEGAUP_ENABLE_SOCIAL_MEDIA_RESOURCES', false);
+          define('OMEGAUP_GITSERVER_URL', 'http://gitserver:33861');
+          define('OMEGAUP_GRADER_URL', 'https://grader:21680');
+          define('OMEGAUP_GITSERVER_SECRET_TOKEN', 'secret');
+          define('REDIS_HOST', 'redis');
+          define('REDIS_PASS', '');
+          define('TEMPLATE_CACHE_DIR', '/tmp');
+          define('OMEGAUP_CSRF_HOSTS', ['frontend', '127.0.0.1']);
+          EOF
+
+          cat > ~/.my.cnf << EOF
+          [client]
+          port=13306
+          host=mysql
+          protocol=tcp
+          user=root
+          password=omegaup
+          EOF
+
+      - name: Initialize database
+        run: |
+          mysql \
+            -e 'CREATE USER "omegaup"@"localhost" IDENTIFIED BY "omegaup";'
+          # Create directory to prevent --purge from failing.
+          sudo mkdir -p /var/lib/omegaup
+          sudo chown "$(id -u)":"$(id -g)" /var/lib/omegaup
+          python3 stuff/bootstrap-environment.py --purge --verbose
 
       - name: Run Python tests
         run: |
