Add tests for `ta`
Co-authored-by: Aritra <aritramajumder8438@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -527,3 +527,117 @@ jobs:
         with:
           name: python-test-logs
           path: /tmp/container-logs/*.log
+
+  teaching-assistant:
+    runs-on: ubuntu-22.04
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Install wait-for-it
+        run: |
+          sudo apt-get update -y && sudo apt-get install -y wait-for-it
+
+      - name: Download the Docker containers
+        run: |
+          docker compose pull
+
+      - name: Clean up existing Docker volumes
+        run: |
+          # Ensure any existing containers and volumes are removed
+          docker compose down -v || true
+          # Make sure any orphaned volumes are cleaned up
+          docker volume rm -f omegaup_omegaupdata omegaup_dbdata omegaup_rabbitmq omegaup_redis || true
+
+      - name: Start the Docker containers
+        run: |
+          docker compose up --no-build --detach
+
+          # Add the container names as aliases to localhost
+          cat << EOF | sudo tee --append /etc/hosts
+          127.0.0.1 mysql grader runner gitserver broadcaster redis
+          EOF
+
+          # Wait for some of the containers
+          wait-for-it -t 30 mysql:13306
+          wait-for-it -t 30 gitserver:33861
+          wait-for-it -t 30 redis:6379
+
+          for i in $(seq 10); do
+            if [[ "$(mysql \
+                     -uomegaup -pomegaup --host=mysql --port=13306 --skip-column-names --batch \
+                     -e 'SELECT 1;' || echo 0)" == "1" ]]; then
+              break
+            fi
+            sleep 1
+          done
+
+      - name: Create default configuration files
+        run: |
+          cat > frontend/server/config.php <<EOF
+          <?php
+          define('OMEGAUP_ALLOW_PRIVILEGE_SELF_ASSIGNMENT', true);
+          define('OMEGAUP_CSP_LOG_FILE', '/tmp/csp.log');
+          define('OMEGAUP_DB_HOST', 'mysql:13306');
+          define('OMEGAUP_DB_NAME', 'omegaup');
+          define('OMEGAUP_DB_PASS', 'omegaup');
+          define('OMEGAUP_DB_USER', 'omegaup');
+          define('OMEGAUP_ENVIRONMENT', 'development');
+          define('OMEGAUP_LOG_FILE', '/tmp/omegaup.log');
+          define('OMEGAUP_ENABLE_SOCIAL_MEDIA_RESOURCES', false);
+          define('OMEGAUP_GITSERVER_URL', 'http://gitserver:33861');
+          define('OMEGAUP_GRADER_URL', 'https://grader:21680');
+          define('OMEGAUP_GITSERVER_SECRET_TOKEN', 'secret');
+          define('REDIS_HOST', 'redis');
+          define('REDIS_PASS', '');
+          define('TEMPLATE_CACHE_DIR', '/tmp');
+          define('OMEGAUP_CSRF_HOSTS', ['frontend', '127.0.0.1']);
+          EOF
+
+          cat > ~/.my.cnf << EOF
+          [client]
+          port=13306
+          host=mysql
+          protocol=tcp
+          user=root
+          password=omegaup
+          EOF
+
+      - name: Install Python dependencies
+        run: |
+          python3 -m pip install --user setuptools
+          python3 -m pip install --user wheel
+          python3 -m pip install --user \
+            -r stuff/requirements.txt
+
+      - name: Install composer dependencies
+        run: composer install --prefer-dist --no-progress
+
+      - name: Initialize database
+        run: |
+          mysql \
+            -e 'CREATE USER "omegaup"@"localhost" IDENTIFIED BY "omegaup";'
+          # Create directory to prevent --purge from failing.
+          sudo mkdir -p /var/lib/omegaup
+          sudo chown "$(id -u)":"$(id -g)" /var/lib/omegaup
+          docker compose exec --user "$(id -u)":"$(id -g)" -T frontend bash -c "\
+            python3 -m venv /opt/omegaup/stuff/venv && \
+            python3 -m pip install wheel && \
+            python3 -m pip install -r /opt/omegaup/stuff/requirements.txt"
+          docker compose exec -T frontend python3 stuff/bootstrap-environment.py --purge --verbose
+
+      - name: Install yarn dependencies
+        run: yarn install
+
+      - name: Build webpack resources
+        run: yarn build
+
+      - name: Wait for dependencies
+        run: |
+          wait-for-it -t 30 grader:21680
+
+      - name: Run pytest
+        run: |
+          pytest stuff/teaching_assistant/ -s
