Cargando información en la base de datos de omegaup para pruebas de python

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -500,26 +500,46 @@ jobs:
 
       - name: Start the Docker containers
         run: |
-           docker-compose up --no-build --detach
+          docker-compose up --no-build --detach
 
-           # Add the container names as aliases to localhost
-           cat << EOF | sudo tee --append /etc/hosts
-           127.0.0.1 rabbitmq mysql
-           EOF
+          # Add the container names as aliases to localhost
+          cat << EOF | sudo tee --append /etc/hosts
+          127.0.0.1 rabbitmq mysql
+          EOF
 
-           # Wait for some of the containers
-           wait-for-it -t 30 mysql:13306
-           wait-for-it -t 30 rabbitmq:5672
-           docker-compose exec -T rabbitmq rabbitmqctl await_startup
+          # Wait for some of the containers
+          wait-for-it -t 30 mysql:13306
+          wait-for-it -t 30 rabbitmq:5672
+          docker-compose exec -T rabbitmq rabbitmqctl await_startup
 
-           for i in $(seq 10); do
-             if [[ "$(mysql \
-                      -uomegaup -pomegaup --host=mysql --port= 13306 --skip-column-names --batch \
-                      -e 'SELECT 1;' || echo 0)" == "1" ]]; then
-               break
-             fi
-             sleep 1
-           done
+          for i in $(seq 10); do
+            if [[ "$(mysql \
+                    -uomegaup -pomegaup --host=mysql --port= 13306 --skip-column-names --batch \
+                    -e 'SELECT 1;' || echo 0)" == "1" ]]; then
+              break
+            fi
+            sleep 1
+          done
+
+      - name: Create default configuration files
+        run: |
+          cat > ~/.my.cnf << EOF
+          [client]
+          port=13306
+          host=mysql
+          protocol=tcp
+          user=root
+          password=omegaup
+          EOF
+
+      - name: Initialize database
+        run: |
+          mysql \
+            -e 'CREATE USER "omegaup"@"localhost" IDENTIFIED BY "omegaup";'
+          # Create directory to prevent --purge from failing.
+          sudo mkdir -p /var/lib/omegaup
+          sudo chown "$(id -u)":"$(id -g)" /var/lib/omegaup
+          python3 stuff/bootstrap-environment.py --purge --verbose
 
       - name: Run Python tests
         run: |
